### ISSUE TITLE
synthesis_capabilities

### ISSUE THREAD

**Issue by zakidotai** [gomesgroup/coscientist#3]
1. There is no directory in the main repo by the name **synthesis_capabilities** but it is described in the README file
2. The example given in the [simple_implementation](https://github.com/gomesgroup/coscientist/tree/main/simple_implementation) is fine. Can you also please update it by providing an end-to-end example which requires performing all the steps as shown in the paper?

**Comment by kuanlinhuang** [comment]
Second this comment!

**Comment by bbanzai88** [comment]
That would be very nice!!

**Comment by DaniilBoiko** [comment]
Sorry for the delay.

1. Added the missing file in 482c0615d0c09181f6100babeb47e02953d763b9.
2. Unfortunately, due to safety reasons, we cannot release the full pipeline (see https://www.nature.com/articles/s41586-023-06792-0#data-availability).
